name: multi-modal-rag
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - bleach=4.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - comm=0.2.1
  - cyrus-sasl=2.1.28
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - expat=2.6.2
  - gettext=0.21.0
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.1
  - idna=3.7
  - ipykernel=6.28.0
  - ipython=8.25.0
  - ipywidgets=8.1.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.10
  - krb5=1.20.1
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcxx=14.0.6
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libglib=2.78.4
  - libiconv=1.16
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libpq=12.17
  - libsodium=1.0.18
  - libxml2=2.13.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mysql=5.7.24
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.0.8
  - notebook-shim=0.2.3
  - openssl=3.0.14
  - overrides=7.4.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pip=24.2
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.12.4
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - qtconsole=5.5.1
  - qtpy=2.4.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - send2trash=1.8.2
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - urllib3=2.2.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - widgetsnbextension=4.0.10
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==3.7.1
      - arrow==1.3.0
      - asgiref==3.8.1
      - asyncer==0.0.2
      - backoff==2.2.1
      - bcrypt==4.2.0
      - bidict==0.23.1
      - build==1.2.1
      - cachetools==5.5.0
      - chainlit==1.1.402
      - chevron==0.14.0
      - chroma-hnswlib==0.7.6
      - chromadb==0.5.5
      - click==8.1.7
      - coloredlogs==15.0.1
      - dataclasses-json==0.5.14
      - deprecated==1.2.14
      - docstring-parser==0.16
      - fastapi==0.110.3
      - filelock==3.15.4
      - filetype==1.2.0
      - flatbuffers==24.3.25
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - google-api-core==2.19.1
      - google-auth==2.34.0
      - google-cloud-aiplatform==1.63.0
      - google-cloud-bigquery==3.25.0
      - google-cloud-core==2.4.1
      - google-cloud-resource-manager==1.12.5
      - google-cloud-storage==2.18.2
      - google-crc32c==1.5.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.63.2
      - greenlet==3.0.3
      - grpc-google-iam-v1==0.13.1
      - grpcio==1.65.5
      - grpcio-status==1.62.3
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.24.6
      - humanfriendly==10.0
      - importlib-metadata==8.0.0
      - importlib-resources==6.4.3
      - isoduration==20.11.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kubernetes==30.1.0
      - langchain==0.2.14
      - langchain-chroma==0.1.2
      - langchain-community==0.2.12
      - langchain-core==0.2.33
      - langchain-google-vertexai==1.0.8
      - langchain-text-splitters==0.2.2
      - langsmith==0.1.99
      - lazify==0.4.0
      - literalai==0.0.607
      - markdown-it-py==3.0.0
      - marshmallow==3.21.3
      - mdurl==0.1.2
      - mmh3==4.1.0
      - monotonic==1.6
      - mpmath==1.3.0
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - numpy==1.26.4
      - oauthlib==3.2.2
      - onnxruntime==1.19.0
      - opentelemetry-api==1.26.0
      - opentelemetry-exporter-otlp==1.26.0
      - opentelemetry-exporter-otlp-proto-common==1.26.0
      - opentelemetry-exporter-otlp-proto-grpc==1.26.0
      - opentelemetry-exporter-otlp-proto-http==1.26.0
      - opentelemetry-instrumentation==0.47b0
      - opentelemetry-instrumentation-asgi==0.47b0
      - opentelemetry-instrumentation-fastapi==0.47b0
      - opentelemetry-proto==1.26.0
      - opentelemetry-sdk==1.26.0
      - opentelemetry-semantic-conventions==0.47b0
      - opentelemetry-util-http==0.47b0
      - orjson==3.10.7
      - packaging==23.2
      - pillow==10.4.0
      - posthog==3.5.0
      - proto-plus==1.24.0
      - protobuf==4.25.4
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pyjwt==2.9.0
      - pypdf==4.3.1
      - pypika==0.48.9
      - pyproject-hooks==1.1.0
      - python-dotenv==1.0.1
      - python-engineio==4.9.1
      - python-multipart==0.0.9
      - python-socketio==5.11.3
      - requests-oauthlib==2.0.0
      - rich==13.7.1
      - rsa==4.9
      - shapely==2.0.6
      - shellingham==1.5.4
      - simple-websocket==1.0.0
      - sqlalchemy==2.0.32
      - starlette==0.37.2
      - sympy==1.13.2
      - syncer==2.0.3
      - tenacity==8.5.0
      - tokenizers==0.20.0
      - tomli==2.0.1
      - tqdm==4.66.5
      - typer==0.12.4
      - types-python-dateutil==2.9.0.20240316
      - typing-inspect==0.9.0
      - uptrace==1.26.0
      - uri-template==1.3.0
      - uvicorn==0.25.0
      - uvloop==0.20.0
      - vertexai==1.63.0
      - watchfiles==0.20.0
      - webcolors==24.8.0
      - websockets==13.0
      - wrapt==1.16.0
      - wsproto==1.2.0
      - yarl==1.9.4
      - zipp==3.20.0
